refactor app to improve UI (#42)
* refactor app to improve UI

Drawable-canvas uses some internal API which seems to gone:

AttributeError: module 'streamlit.elements.image' has no attribute 'image_to_url'

* table scrolling

* renamed pages directory to prevent clashes with legacy navigation

* changed uploads table to a form

* remove box

* upload layout update

* reorganise uploads page

* refactor segmentations and classification into single page

* put options into containers with borders

* small UI updates

* funtions cleanup. no functionality change

* more function cleaning

* function tidying and doc strings

* function tidying and doc strings

* tidying

* tidying

---------

Co-authored-by: Henry Webel <heweb@dtu.dk>